config/routes.rb
Rails.application.routes.draw do
  resources :notes

  resources :maps

  resources :scores
  resources :weapon_sets
  resources :players
  resources :games do
    collection do
      get :top_combinations
    end
  end

  root to: 'games#index'
end

app/models/weapon_set.rb
class WeaponSet < ActiveRecord::Base
  include Stats
  has_many :games

  def self.popularity
    joins(:games).group("games.weapon_set_id").order("count(games.weapon_set_id) desc")
  end
end

app/controllers/weapon_sets_controller.rb
class WeaponSetsController < ApplicationController
  before_action :set_weapon_set, only: [:show, :edit, :update, :destroy]

  # GET /weapon_sets
  # GET /weapon_sets.json
  def index
    @weapon_sets = WeaponSet.all
  end

  # GET /weapon_sets/1
  # GET /weapon_sets/1.json
  def show
  end

  # GET /weapon_sets/new
  def new
    @weapon_set = WeaponSet.new
  end

  # GET /weapon_sets/1/edit
  def edit
  end

  # POST /weapon_sets
  # POST /weapon_sets.json
  def create
    @weapon_set = WeaponSet.new(weapon_set_params)

    respond_to do |format|
      if @weapon_set.save
        format.html { redirect_to @weapon_set, notice: 'Weapon set was successfully created.' }
        format.json { render :show, status: :created, location: @weapon_set }
      else
        format.html { render :new }
        format.json { render json: @weapon_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weapon_sets/1
  # PATCH/PUT /weapon_sets/1.json
  def update
    respond_to do |format|
      if @weapon_set.update(weapon_set_params)
        format.html { redirect_to @weapon_set, notice: 'Weapon set was successfully updated.' }
        format.json { render :show, status: :ok, location: @weapon_set }
      else
        format.html { render :edit }
        format.json { render json: @weapon_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weapon_sets/1
  # DELETE /weapon_sets/1.json
  def destroy
    @weapon_set.destroy
    respond_to do |format|
      format.html { redirect_to weapon_sets_url, notice: 'Weapon set was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weapon_set
      @weapon_set = WeaponSet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weapon_set_params
      params[:weapon_set]
    end
end

app/helpers/weapon_sets_helper.rb
module WeaponSetsHelper
end

app/views/weapon_sets/_form.html.erb
<%= form_for(@weapon_set) do |f| %>
  <% if @weapon_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weapon_set.errors.count, "error") %> prohibited this weapon_set from being saved:</h2>

      <ul>
      <% @weapon_set.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weapon_sets/edit.html.erb
<h1>Editing weapon_set</h1>

<%= render 'form' %>

<%= link_to 'Show', @weapon_set %> |
<%= link_to 'Back', weapon_sets_path %>

app/views/weapon_sets/index.html.erb
<h1>Listing weapon_sets</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weapon_sets.each do |weapon_set| %>
      <tr>
        <td><%= link_to 'Show', weapon_set %></td>
        <td><%= link_to 'Edit', edit_weapon_set_path(weapon_set) %></td>
        <td><%= link_to 'Destroy', weapon_set, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weapon set', new_weapon_set_path %>

app/views/weapon_sets/new.html.erb
<h1>New weapon_set</h1>

<%= render 'form' %>

<%= link_to 'Back', weapon_sets_path %>

app/views/weapon_sets/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_weapon_set_path(@weapon_set) %> |
<%= link_to 'Back', weapon_sets_path %>